"""
Django settings for csp_grapelli project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+)q37s%ng+=^wri1im!us69g(-k6za5o%$9km0$0r*p2)!zmxy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'dictionary',
    'sport_reserve',
    'import_export',
    'admin_reorder',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'csp_grapelli.urls'

ADMIN_REORDER = (
    {
        'app': 'dictionary',
        'name': "Справочники",
        'label': "Справочники",
        'models': (
                'dictionary.SportKind',
                'dictionary.Sport',
                'dictionary.Group',
                'dictionary.EventType',
                'dictionary.Place',
            )
    },
    {
        'app': 'sport_reserve',
        'label': "Спортивный резерв",
        'name': "Спортивный резерв",
        'models':
            (
                'sport_reserve.Sportsman',
                'sport_reserve.Result',
                'sport_reserve.Trainer',
                'sport_reserve.Event',
            )

    },
    {
        'app': 'auth'
    }



)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
            },
        },
    },
]

WSGI_APPLICATION = 'csp_grapelli.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

LANGUAGES = [('ru', 'Russian'), ('en', 'English')]

TIME_ZONE = 'Etc/GMT+3'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# GRAPPELLI part. See https://django-grappelli.readthedocs.io/en/latest/customization.html

# GRAPPELLI_ADMIN_TITLE = "Отдел подготовки спортивного резерва Мурманской области"
# GRAPPELLI_AUTOCOMPLETE_LIMIT = 7

# Dict containing search patterns for models you cannot (or should not) alter.
# GRAPPELLI_AUTOCOMPLETE_SEARCH_FIELDS
# GRAPPELLI_SWITCH_USER
# GRAPPELLI_SWITCH_USER_ORIGINAL
# GRAPPELLI_SWITCH_USER_TARGET
# GRAPPELLI_CLEAN_INPUT_TYPES
