# Generated by Django 2.1 on 2018-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='Winter',
            field=models.BooleanField(default=False, verbose_name='Зимний вид'),
            preserve_default=False,
        ),
    ]
