# Generated by Django 2.1.2 on 2018-10-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_reserve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='Sport',
        ),
    ]
