# Generated by Django 2.1 on 2018-08-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_reserve', '0002_sport_winter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='Sport',
            field=models.ForeignKey(help_text='Вид спорта, которым занимается спортсмен', null=True, on_delete=django.db.models.deletion.PROTECT, to='sport_reserve.Sport', verbose_name='Вид спорта'),
        ),
    ]
