# Generated by Django 2.1.2 on 2018-11-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_reserve', '0002_remove_trainer_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='SportKind',
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('ТР', 'Тренировочные'), ('МС', 'Всероссийские'), ('ВС', 'Международные')], help_text='Тренировочные, Всероссийские, Международные', max_length=3, verbose_name='Вид мероприятия'),
        ),
    ]
