# Generated by Django 2.1 on 2018-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_reserve', '0003_auto_20180827_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EKP',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='№ ЕКП'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Name',
            field=models.TextField(max_length=100, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Stage',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='Этап соревнований'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='Name',
            field=models.TextField(help_text='Тренировочные, Всероссийские, Международные', max_length=100, verbose_name='Вид мероприятия'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Name',
            field=models.TextField(max_length=100, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='place',
            name='City',
            field=models.TextField(help_text='Населенный пункт (город)', max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='place',
            name='Country',
            field=models.TextField(help_text='Страна проведения мероприятия или соревнования', max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='place',
            name='Region',
            field=models.TextField(blank=True, help_text='Регион, область, республика, провинция...', max_length=50, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='result',
            name='PlaceComment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Занятое место (комментарии)'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='Name',
            field=models.TextField(max_length=100, verbose_name='Название вида спорта'),
        ),
        migrations.AlterField(
            model_name='sportkind',
            name='Name',
            field=models.TextField(max_length=100, verbose_name='Тип спорта'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='Degree',
            field=models.TextField(blank=True, help_text='Разряд или звание, присвоенные спорстмену', max_length=100, null=True, verbose_name='Разряд/звание'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='FIO',
            field=models.TextField(help_text='ФИО спортсмена', max_length=100, verbose_name='Фамилия, Имя, Отчество'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='Organisation',
            field=models.TextField(blank=True, help_text='Физкультурно-спортивная организация', max_length=100, null=True, verbose_name='ФСО'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Email',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='FIO',
            field=models.TextField(help_text='ФИО тренера', max_length=100, verbose_name='Фамилия, Имя, Отчество'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Phone1',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Рабочий телефон'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Phone2',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Мобильный телефон'),
        ),
    ]
