# Generated by Django 2.1 on 2018-08-28 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_reserve', '0005_auto_20180827_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['Country', 'Region', 'City'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='sportkind',
            options={'ordering': ['Name'], 'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплина'},
        ),
        migrations.AddField(
            model_name='result',
            name='SportKind',
            field=models.ForeignKey(default='', limit_choices_to={'Sport'}, on_delete=django.db.models.deletion.PROTECT, related_name='Results', to='sport_reserve.SportKind', verbose_name='Дисциплина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='Groups',
            field=models.ManyToManyField(help_text='Группы', to='sport_reserve.Group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Place',
            field=models.ForeignKey(help_text='Место проведения мероприятия или соревнования', on_delete=django.db.models.deletion.PROTECT, to='sport_reserve.Place', verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Sport',
            field=models.ForeignKey(help_text='Вид спорта', on_delete=django.db.models.deletion.PROTECT, to='sport_reserve.Sport', verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.ForeignKey(help_text='Тренировочные, Всероссийские, Международные', on_delete=django.db.models.deletion.PROTECT, to='sport_reserve.EventType', verbose_name='Вид мероприятия'),
        ),
        migrations.AlterField(
            model_name='sportkind',
            name='Name',
            field=models.CharField(default='', help_text='Название дисциплины (100м, эстафета,...)', max_length=100, verbose_name='Название Дисциплины'),
        ),
    ]
