# Generated by Django 2.1.2 on 2018-10-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(help_text='Страна проведения мероприятия или соревнования', max_length=50, verbose_name='Страна')),
                ('Region', models.CharField(blank=True, help_text='Регион, область, республика, провинция...', max_length=50, null=True, verbose_name='Область')),
                ('City', models.CharField(help_text='Населенный пункт (город)', max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['Country', 'Region', 'City'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Название вида спорта')),
                ('Priority', models.BooleanField(verbose_name='Приоритетный вид спорта')),
                ('Olympic', models.BooleanField(verbose_name='Олимпийский вид спорта')),
                ('Winter', models.BooleanField(verbose_name='Зимний вид')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='SportKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', help_text='Название дисциплины (100м, эстафета,...)', max_length=100, verbose_name='Название Дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплина',
                'ordering': ['Name'],
            },
        ),
    ]
